name: CI/CD Pipeline - Node.js with Docker

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PAT}}" | docker login -u "${{ secrets.DOCKER_USERNAME}}" --password-stdin

      # Step 3: Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hello-node:latest .

      # Step 4: Push Docker image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hello-node:latest

      # Step 5: Deploy to Ubuntu server via SSH
      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/hello-node:latest
            docker stop helloworld || true
            docker rm helloworld || true
            docker run -d --name helloworld -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/hello-node:latest
